# Whether or not to enable invisible item frames glowing when there's no item in them
# This will also make them visible when there's no item in them
item-frames-glow-effect: true

# The item in the center of the recipe
# Recommended to use "/iframe setitem" to change this
recipe-item:
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: LINGERING_POTION
  meta:
    ==: ItemMeta
    meta-type: POTION
    potion-type: minecraft:invisibility

locale:
  reload: "&aConfiguration reloaded"
  player-only: "&cSorry, you must be a player to use this command!"
  added-to-your-inventory: "&aAdded an invisible item frame to your inventory"
  added-to-your-inventory-multiple: "&aAdded %count% invisible item frames to your inventory"
  invisible-itemframe-displayname: "&fInvisible Item Frame"
  invisible-glow-itemframe-displayname: "&fInvisible Glow Item Frame"
  recheck: "&aRechecked %count% item frames."
  recipe-item-updated: "&aRecipe item updated!"
  player-not-exist: "&cThat player does not exist."
  given-item: "&aYou've given an invisible item frame to &e%player%&a's inventory"
  given-multiple: "&aYou've given &e%count%&a invisible item frames to &e%player%&a's inventory"
